#!/bin/bash
# Folio.command — Copy this file to your Desktop and double-click to launch
# Generated by scripts/install.sh

# Resolve project root
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$SCRIPT_DIR/launcher.py" ]; then
    PROJECT="$SCRIPT_DIR"
elif [ -f "$SCRIPT_DIR/../launcher.py" ]; then
    PROJECT="$(cd "$SCRIPT_DIR/.." && pwd)"
else
    PROJECT="/Users/vishal/Library/CloudStorage/OneDrive-Personal/Projects/portfolio_dashboard"
fi

# Cleanup: kills all Folio processes and closes the browser tab on exit
cleanup() {
    echo "Shutting down Folio..."
    pkill -f "python.*app.py" 2>/dev/null
    pkill -f "python.*worker.py" 2>/dev/null
    pkill -f "python.*launcher.py" 2>/dev/null
    lsof -ti:8050 | xargs kill -9 2>/dev/null
    osascript 2>/dev/null <<'EOF'
tell application "Safari"
    set winList to every window
    repeat with w in winList
        set tabList to every tab of w
        repeat with t in tabList
            if URL of t contains "127.0.0.1:8050" or URL of t contains "localhost:8050" then
                close t
            end if
        end repeat
    end repeat
end tell
EOF
    sleep 1
    echo "Folio stopped."
    sleep 1
    osascript -e 'tell application "iTerm2" to close (every window)' 2>/dev/null
    exit 0
}
trap cleanup EXIT SIGINT SIGTERM

# Clear port 8050 if in use from a previous session
echo "Clearing port 8050..."
lsof -ti:8050 | xargs kill -9 2>/dev/null
sleep 1

# Start the app. Prefer the venv outside OneDrive (BUG-027); fall back to the in-project .venv
cd "$PROJECT"
echo "Starting Folio..."
PYTHON="$HOME/.folio/venv/bin/python"
[ -x "$PYTHON" ] || PYTHON="$PROJECT/.venv/bin/python"
"$PYTHON" "$PROJECT/launcher.py" &
LAUNCHER_PID=$!

# Keep alive until the launcher exits
wait $LAUNCHER_PID
